// examples/react-integration.tsx
/**
 * Debugg React Integration Example
 * Demonstrates how to integrate Debugg with React applications
 */

import React from 'react';
import { ErrorHandler, createSentryReporter } from '../src/index';

// 🎨 Initialize Debugg for React application
const debugg = new ErrorHandler({
  serviceName: 'my-react-app',
  environment: process.env.NODE_ENV || 'development',
  defaultSeverity: 'medium'
});

// 🚀 Add Sentry reporter for production error tracking
if (process.env.NODE_ENV === 'production') {
  debugg.addReporter(createSentryReporter('YOUR_SENTRY_DSN'));
}

// 🛡️ Custom Error Boundary with Debugg integration
class DebuggErrorBoundary extends React.Component<{
  children: React.ReactNode;
  onError?: (error: Error, errorInfo: React.ErrorInfo) => void;
}> {
  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    // 📊 Capture error with Debugg
    debugg.handle(error, {
      component: this.constructor.name,
      errorInfo: errorInfo,
      reactVersion: React.version,
      location: window.location.href,
      userAgent: navigator.userAgent
    }).catch(console.error);

    // 🔄 Call optional custom error handler
    if (this.props.onError) {
      this.props.onError(error, errorInfo);
    }
  }

  render() {
    return this.props.children;
  }
}

// 📱 Example React Component with Debugg integration
export function UserProfile() {
  const [user, setUser] = React.useState<{ name: string; email: string } | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);

  // 🔍 Fetch user data with Debugg error handling
  React.useEffect(() => {
    async function fetchUser() {
      try {
        const response = await fetch('/api/user/profile');
        if (!response.ok) {
          throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }
        const userData = await response.json();
        setUser(userData);
      } catch (fetchError) {
        // 🐞 Capture fetch error with Debugg
        await debugg.handle(fetchError, {
          endpoint: '/api/user/profile',
          method: 'GET',
          userId: 'current-user-id',
          component: 'UserProfile'
        });

        setError('Failed to load user profile. Please try again.');
      } finally {
        setLoading(false);
      }
    }

    fetchUser();
  }, []);

  // 💻 Handle form submission with Debugg
  async function handleUpdateProfile(newName: string) {
    try {
      const response = await fetch('/api/user/profile', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: newName })
      });

      if (!response.ok) {
        throw new Error(`Update failed: ${response.statusText}`);
      }

      const updatedUser = await response.json();
      setUser(updatedUser);
      return true;
    } catch (updateError) {
      // 🔧 Capture update error with Debugg
      await debugg.handle(updateError, {
        action: 'update_profile',
        newName,
        currentUser: user,
        endpoint: '/api/user/profile',
        method: 'PUT'
      });

      setError('Failed to update profile. Please try again.');
      return false;
    }
  }

  if (loading) return <div>Loading profile...</div>;
  if (error) return <div className="error">{error}</div>;
  if (!user) return <div>No user data available</div>;

  return (
    <div className="user-profile">
      <h2>{user.name}'s Profile</h2>
      <p>Email: {user.email}</p>
      <UserProfileForm
        currentName={user.name}
        onSubmit={handleUpdateProfile}
      />
    </div>
  );
}

// 📝 Profile Form Component
function UserProfileForm({
  currentName,
  onSubmit
}: {
  currentName: string;
  onSubmit: (newName: string) => Promise<boolean>;
}) {
  const [name, setName] = React.useState(currentName);
  const [updating, setUpdating] = React.useState(false);
  const [formError, setFormError] = React.useState<string | null>(null);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setUpdating(true);
    setFormError(null);

    try {
      const success = await onSubmit(name);
      if (!success) {
        setFormError('Update failed. Please check your input.');
      }
    } catch (submitError) {
      // 🚨 Capture form submission error
      await debugg.handle(submitError, {
        action: 'form_submission',
        formName: 'profile_update',
        fieldValues: { name }
      });
      setFormError('An unexpected error occurred.');
    } finally {
      setUpdating(false);
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <div>
        <label htmlFor="name">Name:</label>
        <input
          id="name"
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          required
        />
      </div>
      {formError && <div className="error">{formError}</div>}
      <button type="submit" disabled={updating}>
        {updating ? 'Updating...' : 'Update Profile'}
      </button>
    </form>
  );
}

// 🎯 Usage Example
function App() {
  return (
    <DebuggErrorBoundary>
      <div className="app">
        <header>
          <h1>My Awesome App</h1>
        </header>
        <main>
          <UserProfile />
        </main>
        <footer>
          <p>Powered by Debugg - Smart Error Handling</p>
        </footer>
      </div>
    </DebuggErrorBoundary>
  );
}

// 📚 Export for usage
export { debugg, DebuggErrorBoundary, App };
export default App;

// examples/svelte-integration.svelte
<!--
 * Debugg Svelte Integration Example
 * Demonstrates comprehensive error handling for Svelte applications
 -->

<script>
  import { onMount } from 'svelte';
  import { ErrorHandler, createConsoleReporter } from '../src/index';

  // 🎨 Initialize Debugg for Svelte application
  const debugg = new ErrorHandler({
    serviceName: 'svelte-app',
    environment: import.meta.env.MODE || 'development',
    defaultSeverity: 'medium'
  });

  // 🚀 Add console reporter for development
  if (import.meta.env.MODE === 'development') {
    debugg.addReporter(createConsoleReporter());
  }

  // 📱 Component state
  let user = null;
  let loading = false;
  let error = null;
  let formError = null;
  let name = '';

  // 🔍 Fetch user data with Debugg error handling
  async function fetchUser() {
    loading = true;
    error = null;

    try {
      const response = await fetch('/api/user/profile');

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }

      user = await response.json();

      // 📊 Log successful fetch
      debugg.handle(new Error('User fetched successfully'), {
        type: 'success',
        endpoint: '/api/user/profile',
        user,
        severityOverride: 'info'
      });
    } catch (fetchError) {
      // 🐞 Capture fetch error with Debugg
      await debugg.handle(fetchError, {
        endpoint: '/api/user/profile',
        method: 'GET',
        component: 'UserProfile',
        action: 'fetch_user'
      });

      error = 'Failed to load user profile. Please try again.';
    } finally {
      loading = false;
    }
  }

  // 💻 Handle form submission with Debugg
  async function handleSubmit() {
    formError = null;

    try {
      const response = await fetch('/api/user/profile', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name })
      });

      if (!response.ok) {
        throw new Error(`Update failed: ${response.statusText}`);
      }

      const updatedUser = await response.json();
      user = updatedUser;

      // 🎉 Log successful update
      debugg.handle(new Error('Profile updated successfully'), {
        type: 'success',
        newName: name,
        severityOverride: 'info'
      });
    } catch (submitError) {
      // 🚨 Capture form submission error
      await debugg.handle(submitError, {
        action: 'form_submission',
        formName: 'profile_update',
        fieldValues: { name },
        component: 'UserProfile'
      });

      formError = 'Failed to update profile. Please try again.';
    }
  }

  // 🎯 Svelte lifecycle with Debugg
  onMount(async () => {
    try {
      await fetchUser();

      // 📊 Log component mount
      debugg.handle(new Error('Component mounted'), {
        type: 'lifecycle',
        component: 'UserProfile',
        severityOverride: 'info'
      });
    } catch (mountError) {
      // 🛡️ Capture mount error
      await debugg.handle(mountError, {
        type: 'lifecycle_error',
        component: 'UserProfile',
        lifecycle: 'onMount'
      });
      error = 'Failed to initialize component';
    }
  });

  // 📝 Global error handler for Svelte
  function handleGlobalError(error, context = {}) {
    debugg.handle(error, {
      ...context,
      framework: 'svelte',
      component: 'UserProfile'
    }).catch(console.error);
  }

  // 📚 Export debugg for other components
  export { debugg, handleGlobalError };
</script>

<svelte:head>
  <title>Debugg Svelte Integration</title>
  <style>
    .user-profile { max-width: 600px; margin: 0 auto; padding: 20px; }
    .error { color: #FF4757; background: #FFE5E5; padding: 10px; border-radius: 4px; margin: 10px 0; }
    .loading { color: #1E90FF; font-style: italic; }
    button { background: #FF4757; color: white; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer; }
    button:hover { background: #FF6348; }
    button:disabled { background: #ccc; cursor: not-allowed; }
    input { width: 100%; padding: 8px; margin: 8px 0; border: 1px solid #ddd; border-radius: 4px; }
    .form-error { color: #FF4757; font-size: 0.9rem; margin: 5px 0; }
  </style>
</svelte:head>

<div class="user-profile">
  <h1>🐞 Debugg Svelte Integration</h1>

  {#if loading}
    <div class="loading">Loading user data...</div>
  {:else if error}
    <div class="error">{error}</div>
    <button on:click={fetchUser}>Retry</button>
  {:else if user}
    <div>
      <h2>{user.name}'s Profile</h2>
      <p><strong>Email:</strong> {user.email}</p>

      <form on:submit|preventDefault={handleSubmit}>
        <div>
          <label for="name">Update Name:</label>
          <input id="name" type="text" bind:value={name} placeholder={user.name} required />
        </div>
        {#if formError}
          <div class="form-error">{formError}</div>
        {/if}
        <button type="submit" disabled={!name.trim()}>
          Update Profile
        </button>
      </form>
    </div>
  {:else}
    <div class="loading">No user data available</div>
  {/if}

  <footer style="margin-top: 20px; padding-top: 20px; border-top: 1px solid #eee;">
    <p>Powered by Debugg - Smart Error Handling for Svelte 🚀</p>
  </footer>
</div>

<!-- 🛡️ Svelte error boundary equivalent -->
{svelte:window on:error={e => {
  handleGlobalError(e, {
    type: 'uncaught_error',
    message: e.message,
    component: 'UserProfile'
  });
}}/>
